language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "UcQZxFeZUl6NlYuUwpnsJm/ty0Ym/A/vFjpxrA3VrSZXbWM/FO8w5ClrmGKV3GQdZhldXwYCxQdNPujnhBsOnoaqQR+1QKk4u6+U+e4OQEo2mzF5LLEt3AEm8c/VlB3mlIuK4nmv6t57AqG0oYy5puSBM5UMqEgEu08jAAnR0uDpsTIMO/IFi+i94CjQMHqm9HlEQxo+Dzx2pzQQUERi2aSBhJBrma8gYSePoa0xvfd3CGvFwf3s5QMjeUXEYXGxJBIAZXjwu3A0o871RUaXHSxZSOljzvSeU8K/hkTuD+44DJpKAFnknQnIyIIzXtQzY0ak45DbBevytV6oaKCnp+GO8h552eUSXbkHvy/JntYKUvnaRnHqY4eSV7RHDz5WPq4pkb7oO3Q5VsweZgldy1Fztpxhnmo2qGbq5TD+EkTC3xV6WY4eOQ57/ds8yeMOm1hVpH9mda8Zc53U1DN0Yzykp4i5pmNWkzY3TbM7mpw7CFBg9MIIvIIoCkzeiGMDJxuk5zyyOhtlS+JRHM2CyZ+R624Bi9fh0VNjygsEdQz1jvKF1+7DkF5TJFOXdcdR4h8ZdYNBl/n/uyGjCQNygMPJyU6CC3iHEcNhSbal7UWYYjvSo1xNUYt7PR615O/AunzYjO/G7U6mueP5FK2uY4mV0OKSrOtjdw1r132inWw="
env:
  secure: "Z48w7YC/thmQiA6pGoKeUHL/KzIn1bsakGxRLA8aUh0Vie/qtNRbi79Um4HT0wyARW1Ddye3mP9TCHvnhby+EfZTVFk9PJKSBK3vMByuMAFwoRPLdXOYXr5eESdfJOHDhQx5358AGtpzI+36GIC9rZ64+segxeBttXiT39QbevOwG6dgsPw82kRSQfxpM3wkE9OywwskT7OYifLtMDM2EtO2a2XbFKU2+gnSlv63UAYEfUUVIHbw9LnpPxdmxzWKbmpvJN6h5FOU0u57i4nlA6Abe8rpJMDZXEOrSfb41Dpr/J2k+P3deIDVWkZlQQFtNxoYqe2H3JcLp/O4WY3E+IBpXNe+T/6O/8zsr/5OTfGyX/dNmMFArJoYtT+j8hAwCzdSvqeMP8cvq80S73jjtYERret7ilUHiTOXblio0sS/p6igtUMrY/9RtLDlhMc5+arz4xlyyDkoEROFIdSDOllwcbwZICAw4THmt6pF11HH6tcSrxdMBScG0R0+tYoHEa+m+fxVfqct3us+PMDF53fi5/xlPlm1W7sKCIQ+hciSoh/Q2DFN70RvJl4U9U2mcNM6uJ8sKUldkkS+FD0kaH2NNVmvQNsgai6sC/q3p749+Qg7xSAqeVtVZ7jYPwAN4/4gtTCMcobkGPEtucy2eeqMJqqRanTQERLOlanRU2E="
