language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "Z48w7YC/thmQiA6pGoKeUHL/KzIn1bsakGxRLA8aUh0Vie/qtNRbi79Um4HT0wyARW1Ddye3mP9TCHvnhby+EfZTVFk9PJKSBK3vMByuMAFwoRPLdXOYXr5eESdfJOHDhQx5358AGtpzI+36GIC9rZ64+segxeBttXiT39QbevOwG6dgsPw82kRSQfxpM3wkE9OywwskT7OYifLtMDM2EtO2a2XbFKU2+gnSlv63UAYEfUUVIHbw9LnpPxdmxzWKbmpvJN6h5FOU0u57i4nlA6Abe8rpJMDZXEOrSfb41Dpr/J2k+P3deIDVWkZlQQFtNxoYqe2H3JcLp/O4WY3E+IBpXNe+T/6O/8zsr/5OTfGyX/dNmMFArJoYtT+j8hAwCzdSvqeMP8cvq80S73jjtYERret7ilUHiTOXblio0sS/p6igtUMrY/9RtLDlhMc5+arz4xlyyDkoEROFIdSDOllwcbwZICAw4THmt6pF11HH6tcSrxdMBScG0R0+tYoHEa+m+fxVfqct3us+PMDF53fi5/xlPlm1W7sKCIQ+hciSoh/Q2DFN70RvJl4U9U2mcNM6uJ8sKUldkkS+FD0kaH2NNVmvQNsgai6sC/q3p749+Qg7xSAqeVtVZ7jYPwAN4/4gtTCMcobkGPEtucy2eeqMJqqRanTQERLOlanRU2E="
